controller_manager:
  ros__parameters:
    update_rate: 20

    rover_base_control:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

rover_base_control:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController #añadido
    use_stamped_vel: false
    use_sim_time: true
    publish_rate: 50.0
    left_wheel_names: ["left_front_wheel_joint", "left_back_wheel_joint", "left_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint", "right_back_wheel_joint", "right_wheel_joint"]
    wheel_separation: 2.47
    wheel_radius: 0.2
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0
    base_frame_id: base_footprint
    enable_odom_tf: true
    publish_limited_velocity: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 1.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 1.0

scara_controller:
  ros__parameters:
    joints:
      - arm_sphere_1_link_joint
      - arm_sphere_2_link_joint
      - extension_cylinder_link_joint
      - base_gripper_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true

gripper_controller:
  ros__parameters:
    joints:
      - left_hand_link_joint
      - right_hand_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true

