# Default initial positions for rover's ros2_control fake system

initial_positions:
  arm_sphere_1_link_joint: 0
  arm_sphere_2_link_joint: 0
  base_gripper_link_joint: 0
  extension_cylinder_link_joint: -1.199
  left_hand_link_joint: 0
  right_hand_link_joint: 0